services:
  data-ingestion:
    container_name: data-ingestion
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7000:7000"
    environment:
      - KAFKA_HOST=kafka
      - KAFKA_PORT=${KAFKA_PORT}
      - KAFKA_TOPIC=network.data.ingested
      - CORS_ORIGINS=http://localhost:5173,http://localhost:3000,http://127.0.0.1:5173
      - POLICY_SERVICE_URL=${POLICY_SERVICE_URL}
      - POLICY_COMPONENT_ID=${POLICY_COMPONENT_ID}
      - POLICY_ENABLED=${POLICY_ENABLED}
      - POLICY_ROLENAME=${POLICY_ROLENAME:-Ingestion}
      - HOST=${HOST:-data-ingestion}
      - PORT=7000
      - PRODUCER_MAX_TIMEOUT=30
    networks:
      - nwdaf-network

networks:
  nwdaf-network:
    name: nwdaf-network
